# Generated by Django 3.2.8 on 2021-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalOfficeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_rseti', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('state', models.IntegerField()),
                ('district', models.IntegerField()),
                ('pincode', models.CharField(max_length=200)),
                ('office_email', models.CharField(max_length=200)),
                ('concerned_official', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('landline_no', models.CharField(max_length=200)),
                ('email_add', models.CharField(max_length=200)),
                ('details_update', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecondInstalmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondInstalmentRequestLetterFile', models.CharField(blank=True, max_length=200)),
                ('formGFR12AFile', models.CharField(blank=True, max_length=200)),
                ('formFormat3File', models.CharField(blank=True, max_length=200)),
                ('intrestFirstInstallmentFile', models.CharField(blank=True, max_length=200)),
                ('firstInstallmentAmountFile', models.CharField(blank=True, max_length=200)),
                ('declarationOfBankFile', models.CharField(blank=True, max_length=200)),
                ('photoesOfBuildings', models.CharField(blank=True, max_length=200)),
                ('notionalIntrest', models.CharField(max_length=200)),
                ('approvalOfNIRDPR', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('postal_address', models.CharField(max_length=500)),
                ('rseti_department', models.CharField(max_length=200)),
                ('department_address', models.CharField(max_length=200)),
                ('top_executives', models.CharField(max_length=200)),
                ('landline_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrustAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_trust', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('state', models.IntegerField()),
                ('district', models.IntegerField()),
                ('pincode', models.CharField(max_length=200)),
                ('bank_acc_no', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('back_acc_type', models.CharField(max_length=200)),
                ('back_acc_ifs', models.CharField(max_length=200)),
                ('registration_certificate', models.CharField(max_length=2000)),
                ('pan_card', models.CharField(max_length=2000)),
                ('it_exemption', models.CharField(max_length=2000)),
                ('mou_file', models.CharField(max_length=2000)),
            ],
        ),
    ]
