# Generated by Django 3.2.8 on 2021-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rseti', '0002_secondinstalmentrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondinstalmentrequest',
            name='declarationOfBankFile',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondinstalmentrequest',
            name='firstInstallmentAmountFile',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondinstalmentrequest',
            name='formFormat3File',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondinstalmentrequest',
            name='formGFR12AFile',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondinstalmentrequest',
            name='intrestFirstInstallmentFile',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondinstalmentrequest',
            name='photoesOfBuildings',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='secondinstalmentrequest',
            name='secondInstalmentRequestLetterFile',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
    ]
